add in mirror support

diff --git a/pkgmk.in b/pkgmk.in
--- a/pkgmk.in
+++ b/pkgmk.in
@@ -22,6 +22,19 @@
 #  USA.
 #
 
+array() {
+	printf "${2}" | tr --delete '\n' | sed \
+		-e 's|[\t| ]\+| |g' | \
+		cut --delimiter=' ' --fields="${1}"
+}
+
+array_count() {
+	printf "${1}" | tr --delete '\n' | sed \
+		-e 's|[\t| ]\+| |g' \
+		-e 's|^ ||' \
+		-e 's| $||'	| wc --words
+}
+
 info() {
 	echo "=======> $1"
 }
@@ -47,6 +60,21 @@ get_filename() {
 get_basename() {
 	local FILE="`echo $1 | sed 's|^.*://.*/||g'`"
 	echo $FILE
+}
+
+get_scheme() {
+	local SCHEME="`echo $1 | sed 's|\(^.*\)://.*|\1|g'`"
+	echo $SCHEME
+}
+
+get_mirror_name() {
+	local NAME="`echo $1 | sed 's|^.*://||' | sed -e 's|/.*||'`"
+	echo $NAME
+}
+
+get_mirror_path() {
+	local URL="`echo $1 | sed "s|^.*://$2/||"`"
+	echo $URL
 }
 
 check_pkgfile() {
@@ -164,7 +192,7 @@ download_file() {
 }
 
 download_source() {
-	local FILE LOCAL_FILENAME
+	local FILE LOCAL_FILENAME SCHEME PKG_SOURCE_MIRRORS PKG_SOURCE_MIRROR MIRROR_NAME
 
 	for FILE in ${source[@]}; do
 		LOCAL_FILENAME="$(get_filename "${FILE}")"
@@ -174,7 +202,21 @@ download_source() {
 				exit 1
 			else
 				if [ "${PKGMK_DOWNLOAD}" = 'yes' ]; then
-					download_file "${FILE}"
+					SCHEME="$(get_scheme "${FILE}")"
+					if [ "${SCHEME}" = 'mirror' ]; then
+						unset MIRROR_NAME PKG_SOURCE_MIRRORS PKG_SOURCE_MIRROR MIRROR_TOTAL
+						MIRROR_NAME="$(get_mirror_name "${FILE}")"
+						if [ ! -e "/etc/ports/mirrors/${MIRROR_NAME}" ]; then
+							error "Error '/etc/ports/mirrors/${MIRROR_NAME}' does not exist."
+						fi
+						PKG_SOURCE_MIRRORS="$(cat "/etc/ports/mirrors/${MIRROR_NAME}" | xargs)" || error "Error in mirror list."
+						MIRROR_TOTAL="$(array_count "${PKG_SOURCE_MIRRORS}")"
+						PKG_SOURCE_MIRROR="$(( $(perl -e "print int( rand( ${MIRROR_TOTAL} ) );") + 1))"
+						download_file "$(array "${PKG_SOURCE_MIRROR}" "${PKG_SOURCE_MIRRORS}")$(get_mirror_path "${FILE}" "${MIRROR_NAME}")" || \
+							error "Error in mirror download."
+					else
+						download_file "${FILE}"
+					fi
 				else
 					error "Source file '${LOCAL_FILENAME}' not found (use option -d to download)."
 					exit 1
